apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-component
  namespace: argocd
spec:
  project: infrastructure
  sources:
    - repoURL: https://kubernetes-sigs.github.io/external-dns/
      chart: external-dns
      targetRevision: 1.18.0
    - repoURL: https://gitlab.com/vladbilii/self-hosted-cluster-cv.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true