apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: pyspark-job
spec:
  type: Python
  pythonVersion: 3
  mode: cluster
  image:  "registry.gitlab.com/vladbilii/self-hosted-cluster-cv/spark:5d6f6d3c3f93b2121f2fd269e1fcaa458e1e6fd4"
  mainApplicationFile: "local:///opt/spark/test-image/main.py" 
  driver:
    cores: 1
    memory: "1g"
  executor:
    cores: 1
    memory: "1g"
    instances: 2