apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-vpc-cni
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: production
  ignoreDifferences:
  - group: ""
    kind: ServiceAccount
    name: aws-node
    namespace: kube-system
    jsonPointers:
    - /metadata/annotations/eks.amazonaws.com~1role-arn
  syncPolicy:
    syncOptions:
      - CreateNamespace=true