apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../base

patches:
  - target:
      kind: Application
      name: ingress-nginx-component
    patch: |
      - op: add
        path: /spec/sources/0/helm
        value:
          valueFiles:
            - $values/IAM/kubernetes/components/nginx-ingress-controller/overlays/production/oidc/values.yaml