controller:
  ingressClassResource:
    enabled: true
    name: oidc-nginx-ingress
  config:
    strict-validate-path-type: false
service:
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing