---
- name: Fetch cluster phase from SSM
  hosts: localhost
  roles:
    - role: kubernetes_cluster_phase
      when: DEPARTMENT  == "production"

- name: Configure HAProxy server
  hosts: haproxy
  become: true
  gather_facts: true
  roles:
    - role: haproxy_server
      when: DEPARTMENT  == "production"

- name: Bake AMI
  hosts: >-
    {{
      'default' if (PACKER_AMI_BUILD is defined and (PACKER_AMI_BUILD | bool)) else 
      'none'if (PACKER_AMI_USE is defined and (PACKER_AMI_USE | bool)) else
      'worker:controlplane'
    }}
  become: true
  gather_facts: true
  roles:
    - role: kubernetes_cluster_ami
  tags: [packer]

- name: Init primary controlplane node
  hosts: >-
    {{
      'none'if (PACKER_AMI_BUILD is defined and (PACKER_AMI_BUILD | bool)) else
      groups['controlplane'][0]
    }}
  become: true
  gather_facts: true
  roles:
    - role: kubernetes_cluster_init

- name: Join other nodes
  hosts: >-
    {{
      'none'if (PACKER_AMI_BUILD is defined and (PACKER_AMI_BUILD | bool)) else
      groups['controlplane'][1:] + groups['worker']
    }}
  become: true
  gather_facts: true
  roles:
    - role: kubernetes_cluster_join
