apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Application
      name: external-secrets-component
    patch: |
      - op: add
        path: /spec/sources/0/helm
        value:
          valueFiles:
            - $values/IAM/kubernetes/components/external-secret-operator/overlays/production/values.yaml