apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-operator-component
  namespace: argocd
spec:
  project: infrastructure
  sources:
    - repoURL: https://apache.github.io/spark-kubernetes-operator 
      chart: spark-kubernetes-operator
      targetRevision: 1.5.0
    - repoURL: https://gitlab.com/vladbilii/self-hosted-cluster-cv.git
      targetRevision: feature/spark-deploy
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: spark
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true