apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: airflow
  source:
    repoURL: https://gitlab.com/vladbilii/self-hosted-cluster-cv.git
    targetRevision: feature/spark-deploy
    path: IAM/kubernetes/components/airflow/overlays/development/
  destination:
    server: https://kubernetes.default.svc
    namespace: airflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true