apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: airflow-spark-role
  namespace: spark
  annotations:
    argocd.argoproj.io/sync-wave: "3"
rules:
  - apiGroups: ["sparkoperator.k8s.io"]
    resources: ["sparkapplications", "sparkapplications/status"]
    verbs: ["create", "get", "list", "watch", "delete"]

  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]

  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]

  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow-spark-role-binding
  namespace: spark
  annotations:
    argocd.argoproj.io/sync-wave: "3"
subjects:
  - kind: ServiceAccount
    name: airflow-component-worker
    namespace: airflow
roleRef:
  kind: Role
  name: airflow-spark-role
  apiGroup: rbac.authorization.k8s.io