#Kubernetes version
K8S_VERSION: "1.33"
K8S_PATCH: "2"
K8S_PACKAGE: "1.1"
K8S_UPSTREAM_VERSION: "{{ K8S_VERSION }}.{{ K8S_PATCH }}"
K8S_FULL_VERSION: "{{ K8S_VERSION }}.{{ K8S_PATCH }}-{{ K8S_PACKAGE }}"

#Additional versions
CONTAINERD_VERSION: "2.1.3"
RUNC_VERSION: "1.3.0"
CNI_VERSION: "1.6.2"
HELM_VERSION: "3.18.2"
GO_VERSION: "1.25.1"
