apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-alb-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: production
  source:
    repoURL: https://aws.github.io/eks-charts
    chart: aws-load-balancer-controller 
    targetRevision: 1.13.3
    helm:
      values: |
        nodeSelector:
          node-role.kubernetes.io/control-plane: ""
        tolerations:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
            effect: NoSchedule
        clusterName: production-cluster
        serviceAccount:
          create: true
        region: eu-central-1
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true