apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-vpc-cni
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: production
  source:
    repoURL: https://aws.github.io/eks-charts
    chart: aws-vpc-cni
    targetRevision: 1.20.0
    helm:
      values: |
        env:
          ENABLE_PREFIX_DELEGATION: "true"
          NETWORK_POLICY_ENFORCING_MODE: "standard"
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true