apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-oidc-prod
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  acme:
    email: vladshepardcr7@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-oidc-prod-key
    solvers:
      - http01:
          ingress:
            ingressClassName: oidc-nginx-ingress