apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-component
  namespace: fastapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: "registry.gitlab.com/vladbilii/self-hosted-cluster-cv:6178aedcd15039520f1ec2e2982ea7c53cec5e1b"
          command: ['uvicorn', 'app.main:app', '--host', '0.0.0.0', '--port', '8080']
          ports:
            - name: http
              containerPort: 8080
