apiVersion: batch/v1
kind: Job
metadata:
  name: alembic-migrate
  namespace: postgres
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: fastapi
          image: "registry.gitlab.com/vladbilii/self-hosted-cluster-cv:6178aedcd15039520f1ec2e2982ea7c53cec5e1b"
          imagePullPolicy: IfNotPresent
          command: ["sh", "-lc"]
          args:
            - alembic upgrade head
