apiVersion: batch/v1
kind: Job
metadata:
  name: alembic-migrate
  namespace: postgres
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: fastapi
          image: "registry.gitlab.com/vladbilii/self-hosted-cluster-cv:5d6f6d3c3f93b2121f2fd269e1fcaa458e1e6fd4"
          imagePullPolicy: IfNotPresent
          command: ["sh", "-lc"]
          args:
            - alembic upgrade head