apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastapi-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: fastapi
  source:
    repoURL: https://gitlab.com/vladbilii/self-hosted-cluster-cv.git
    targetRevision: feature/fastapi-deploy
    path: IAM/kubernetes/components/fastapi/overlays/development/
  destination:
    server: https://kubernetes.default.svc
    namespace: fastapi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true