apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster-issuer.yaml
  - cluster-role.yaml
  - cluster-role-binding.yaml
  - ingress-cert.yaml
  - main-ingress-resource.yaml
  - redirect-ingress-resource.yaml
  
