apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: dex
    repo: https://charts.dexidp.io
    version: 0.23.0
    releaseName: dex
    namespace: dex
    valuesInline:
      ingress:
        enabled: false
      config:
        issuer: https://dex.vladbilii.click
        storage:
          type: etcd
          config:
            endpoints:
              - http://etcd.kube-system.svc.cluster.local:2379
            namespace: kube-system
        enablePasswordDB: true

resources:
  - ingress-class.yaml
  - ingress-resource.yaml
  
