apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow-root
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: airflow
  source:
    repoURL: https://github.com/vladBili/self-hosted-cluster-cv.git
    targetRevision: main
    path: IAM/kubernetes/applications/development/airflow
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true