apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-root
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: spark
  source:
    repoURL: https://gitlab.com/vladbilii/self-hosted-cluster-cv.git
    targetRevision: feature/spark-deploy
    path: IAM/kubernetes/applications/development/spark
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true