apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ccm
  namespace: argocd
spec:
  project: development
  source:
    repoURL: https://github.com/vladBili/self-hosted-cluster-cv.git
    targetRevision: main
    path: IAM/kubernetes/base/ccm/kustomize
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true