---
- name: Kubernetes
  hosts: localhost
  environment:
    KUBECONFIG: "{{ directory }}/IAM/kubernetes/env/{{ department }}/config/admin.conf"
  tasks:
    - name: Label nodes
      ansible.builtin.command:
        cmd: kubectl label node {{ item }} node-role.kubernetes.io/worker=
      loop: "{{ groups['worker'] }}"

    - name: Deploy CNI
      ansible.builtin.command:
        cmd: kubectl apply -k "{{ directory }}/IAM/kubernetes/overlays/{{ department }}/cni"

    - name: Setup for production
      when: department == "production"
      block:
        - name: Deploy CCM
          ansible.builtin.command:
            cmd: kubectl apply -k "{{ directory }}/IAM/kubernetes/overlays/{{ department }}/ccm"

        - name: Deploy ALB controller
          ansible.builtin.shell: |
            helm repo add eks https://aws.github.io/eks-charts || true
            helm repo update
            helm upgrade --install aws-load-balancer-controller eks/aws-load-balancer-controller -n kube-system \
            --set nodeSelector."node-role\.kubernetes\.io/control-plane"="" \
            --set tolerations[0].key="node-role.kubernetes.io/control-plane" \
            --set tolerations[0].operator="Exists" \
            --set tolerations[0].effect="NoSchedule" \
            --set clusterName="{{ department }}-cluster" \
            --set serviceAccount.create=true \
            --set region={{ region }}

        - name: Wait until ALB controller deployment is ready
          kubernetes.core.k8s_info:
            kind: Deployment
            name: aws-load-balancer-controller
            namespace: kube-system
          register: deploy_info
          until: deploy_info.resources[0].status.readyReplicas == deploy_info.resources[0].status.replicas
          retries: 20
          delay: 15

        - name: Deploy Kustomize
          ansible.builtin.command:
            cmd: kubectl apply -k "{{ directory }}/IAM/kubernetes/overlays/{{ department }}"
