---
- name: Kubernetes
  hosts: localhost
  environment:
    KUBECONFIG: "{{ directory }}/IAM/kubernetes/env/{{ department }}/config/admin.conf"
  tasks:
    - name: Label nodes
      ansible.builtin.command:
        cmd: kubectl label node {{ item }} node-role.kubernetes.io/worker=
      loop: "{{ groups['worker'] }}"

    - name: Deploy CNI
      ansible.builtin.shell: |
        helm repo add eks https://aws.github.io/eks-charts || true
        helm repo update
        helm upgrade --install aws-vpc-cni eks/aws-vpc-cni \
        --namespace kube-system \
        --version 1.20.0 \
        --set env.ENABLE_PREFIX_DELEGATION=true \
        --set env.NETWORK_POLICY_ENFORCING_MODE=standard

    - name: Deploy CCM
      ansible.builtin.shell: |
        kubectl apply -k https://github.com/kubernetes/cloud-provider-aws//examples/existing-cluster/base?ref=master

    - name: Deploy ArgoCD
      vars:
        cp_count: "{{ groups['controlplane'] | length }}"
        ha_enabled: "{{ 'true' if department == 'production' else 'false' }}"
      ansible.builtin.shell: |
        helm repo add argo https://argoproj.github.io/argo-helm || true
        helm repo update
        helm upgrade --install argocd argo/argo-cd \
          --create-namespace \
          --namespace argocd \
          --set redis-ha.enabled={{ ha_enabled }} \
          --set controller.replicas={{ cp_count }} \
          --set server.replicas={{ cp_count }} \
          --set repoServer.replicas={{ cp_count }} \
          --set applicationSet.replicas={{ cp_count }}

    - name: Deploy argocd projects
      ansible.builtin.shell: |
        kubectl apply -f "{{ directory }}/IAM/argocd/{{ department }}/projects"

    - name: Deploy applications
      ansible.builtin.shell: |
        kubectl apply -k "{{ directory }}/IAM/kubernetes/overlays/{{ department }}"

    - name: Wait until OIDC is ready and retrieve thumprint to AWS SSM parameter
      when: department  == "production"
      block:
        - name: Wait until OIDC endpoint is available
          ansible.builtin.uri:
            url: "https://oidc.{{ domain_name }}/.well-known/openid-configuration"
            method: GET
            return_content: no
            status_code: 200
            validate_certs: yes
          register: oidc_ready
          until: oidc_ready.status == 200
          retries: 60
          delay: 25
          ignore_errors: no

        - name: Get OIDC thumbprint
          ansible.builtin.shell: |
            echo | openssl s_client -servername oidc.{{ domain_name }} -connect oidc.{{ domain_name }}:443 2>/dev/null \
            | openssl x509 -fingerprint -noout \
            | sed 's/.*=//;s/://g' | tr '[:upper:]' '[:lower:]'
          register: oidc_thumbprint
          changed_when: false

        - name: Save OIDC thumbprint to tfvars file
          ansible.builtin.copy:
            dest: "{{ directory }}/IAM/kubernetes/overlays/{{ department }}/oidc/thumbprint.tfvars"
            content: |
              oidc_thumbprint = "{{ oidc_thumbprint.stdout }}"

- name: OIDC
  hosts: controlplane
  become: true
  tasks:
    - name: Insert OIDC options
      when: department  == "production"
      block:
        - name: Ensure OIDC service-account-issuer is present before default issuer
          ansible.builtin.lineinfile:
            path: /etc/kubernetes/manifests/kube-apiserver.yaml
            insertbefore: ".*--service-account-issuer=https://kubernetes.default.svc.cluster.local"
            line: "    - --service-account-issuer=https://oidc.{{ domain_name }}"
            state: present

        - name: Ensure OIDC service-account-jwks-uri is present after default service-account-issuer
          ansible.builtin.lineinfile:
            path: /etc/kubernetes/manifests/kube-apiserver.yaml
            insertafter: ".*--service-account-issuer=https://kubernetes.default.svc.cluster.local"
            line: "    - --service-account-jwks-uri=https://oidc.{{ domain_name }}/.well-known/jwks.json"
            state: present

- name: IRSA roles
  hosts: localhost
  environment:
    KUBECONFIG: "{{ directory }}/IAM/kubernetes/env/{{ department }}/config/admin.conf"
  tasks:
    - name: Implement IRSA for pods
      when: department  == "production"
      block:
        - name: Load IRSA mappings
          ansible.builtin.include_vars:
            file: "{{ directory }}/IAM/kubernetes/overlays/{{ department }}/irsa/sa.yaml"
            name: irsa
          ignore_errors: yes

        - name: Annotate service accounts
          ansible.builtin.shell: |
            kubectl annotate sa {{ item.sa_name }} \
              -n {{ item.sa_namespace }} \
              eks.amazonaws.com/role-arn={{ item.sa_role_arn }} --overwrite
          loop: "{{ irsa.mapping }}"
          ignore_errors: yes

        - name: Restart test deployment
          ansible.builtin.shell: |
            kubectl rollout restart deployment/irsa-test-deployment -n default
          ignore_errors: yes
