apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-vpc-cni-component
  namespace: argocd
spec:
  project: infrastructure
  sources:
    - repoURL: https://aws.github.io/eks-charts
      chart: aws-vpc-cni
      targetRevision: 1.20.0
    - repoURL: https://gitlab.com/vladbilii/self-hosted-cluster-cv.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true