apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-ebs-csi-component
  namespace: argocd
spec:
  project: infrastructure
  sources:
    - repoURL: https://kubernetes-sigs.github.io/aws-ebs-csi-driver
      chart: aws-ebs-csi-driver
      targetRevision: 2.49.1
    - repoURL: https://github.com/vladBili/self-hosted-cluster-cv.git
      targetRevision: feature/airflow-deploy
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true