apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: spark
  source:
    repoURL: https://gitlab.com/vladbilii/self-hosted-cluster-cv.git
    targetRevision: feature/spark-deploy
    path: IAM/kubernetes/components/spark/overlays/development/
  destination:
    server: https://kubernetes.default.svc
    namespace: spark
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true