- name: Check if cluster is already initialized
  ansible.builtin.stat:
    path: /etc/kubernetes/admin.conf
  register: KUBEADM_CONFIG

- name: Create temporary kubernetes directory
  ansible.builtin.file:
    path: /tmp/kubernetes
    state: directory
  register: KUBERNETES_TEMP_DIR

- name: Copy init cluster yaml to controlplane
  ansible.builtin.copy:
    src: "{{ DIRECTORY }}/IAM/kubernetes/env/{{ DEPARTMENT }}/init/cluster_conf.yaml"
    dest: "{{ KUBERNETES_TEMP_DIR.path }}/k8s_cluster_conf.yaml"
  register: KUBERNETES_INIT_FILE

- name: Cluster setup block
  when: not KUBEADM_CONFIG.stat.exists
  block:
    - name: Check apiserver DNS resolution
      when: DEPARTMENT == "production"
      ansible.builtin.getent:
        database: hosts
        key: "k8s.{{ DOMAIN_NAME }}"
      register: dns_check
      until: dns_check is succeeded
      retries: 60
      delay: 25
      ignore_errors: no

    - name: Initialize cluster
      ansible.builtin.command:
        cmd: kubeadm init --upload-certs --config {{ KUBERNETES_INIT_FILE.dest }}
      register: KUBEADM_INIT_OUTPUT

    - name: Get join command
      ansible.builtin.command:
        cmd: kubeadm token create --print-join-command
      register: KUBEADM_JOIN_COMMAND

    - name: Create .kube directory
      ansible.builtin.file:
        path: "~/.kube"
        state: directory

    - name: Copy admin.conf to .kube directory
      ansible.builtin.copy:
        src: /etc/kubernetes/admin.conf
        dest: "~/.kube/config"
        remote_src: yes

    - name: Fetch kubeconfig from control plane
      ansible.builtin.fetch:
        src: /etc/kubernetes/admin.conf
        dest: "{{ DIRECTORY }}/IAM/kubernetes/env/{{ DEPARTMENT }}/config/admin.conf"
        flat: yes

    - name: Save join command
      ansible.builtin.set_fact:
        join_token: "{{ (KUBEADM_JOIN_COMMAND.stdout | regex_search('--token\\s+([a-z0-9]+\\.[a-z0-9]+)', '\\1'))[0] }}"
        join_sha256: "{{ (KUBEADM_JOIN_COMMAND.stdout | regex_search('--discovery-token-ca-cert-hash\\s+sha256:([a-f0-9]+)', '\\1'))[0] }}"
        cert_key: "{{ (KUBEADM_INIT_OUTPUT.stdout | regex_findall('--certificate-key\\s+([a-f0-9]+)'))[0] }}"
      run_once: true
      delegate_to: localhost

    - name: Save join command vars into localhost
      ansible.builtin.add_host:
        name: localhost
        join_token: "{{ join_token }}"
        join_sha256: "{{ join_sha256 }}"
        cert_key: "{{ cert_key }}"
      run_once: true
      delegate_to: localhost

    - name: Push kubeadm facts to SSM
      when: DEPARTMENT == "production"
      ansible.builtin.shell: |
        aws ssm put-parameter \
          --name "{{ item.key }}" \
          --value "{{ item.value }}" \
          --type String \
          --overwrite
      delegate_to: localhost
      become: false
      loop:
        - {
            key: "/kubernetes/{{ DEPARTMENT }}/join_token",
            value: "{{ join_token }}",
          }
        - {
            key: "/kubernetes/{{ DEPARTMENT }}/join_sha256",
            value: "{{ join_sha256 }}",
          }
      environment:
        AWS_PROFILE: "{{ DEPARTMENT }}-user"
