dags:
  gitSync:
    subPath: "IAM/airflow/development/dags"

executor: KubernetesExecutor

redis:
  enabled: false

workers:
  replicas: 0

data:
  metadataConnection:
    db: airflow
    user: airflow
    pass: airflow
    protocol: postgresql
    host: airflow-postgres.airflow.svc.cluster.local
    port: 5432
    sslmode: disable

extraEnv: |
  - name: AIRFLOW_CONN_AWS_DEFAULT
    value: "aws://@/?region_name=eu-central-1"

config:
  logging:
    remote_logging: 'True'
    logging_level: 'INFO'
    remote_base_log_folder: "s3://s3-bucket-development-vlad-bilii/airflow/logs"
    remote_log_conn_id: 'aws_default'
    delete_worker_pods: 'False'
    encrypt_s3_logs: 'False'