apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: airflow-metadata-connection
  namespace: airflow
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-asm-airflow
  target:
    name: airflow-connection
    creationPolicy: Owner
  data:
    - secretKey: connection
      remoteRef:
        key: airflow/production/rds_connection