apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: airflow
  source:
    repoURL: https://github.com/vladBili/self-hosted-cluster-cv.git
    targetRevision: feature/airflow-deploy
    path: IAM/kubernetes/components/airflow/overlays/production/
  destination:
    server: https://kubernetes.default.svc
    namespace: airflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true