apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secret
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/vladBili/self-hosted-cluster-cv.git
    targetRevision: feature/airflow-deploy
    path: IAM/kubernetes/components/external-secret-operator/overlays/production
  ignoreDifferences:
  - group: ""
    kind: ServiceAccount
    name: external-secrets
    namespace: external-secrets
    jsonPointers:
    - /metadata/annotations/eks.amazonaws.com~1role-arn
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true