apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oidc
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "9"
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/vladBili/self-hosted-cluster-cv.git
    targetRevision: feature/airflow-deploy
    path: IAM/kubernetes/components/oidc/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: oidc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true